#include "raylib.h"

#define NUM_BLOCKS 12
#define MAX_DATAVALS 26

int blocktile[NUM_BLOCKS][MAX_DATAVALS] = {
    {0},
    {1,2,3,8},
    {4,4,4,4,4,4,4},
    {5,5,5,5,5,5,5},
    {6,6,6,6,6,6,6},
    {7,7,7,7,7,7,7},
    {9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9},
    {10},
    {11,11},
	{'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z'},
	{'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z'},
  {'.',',',';',':'}
};

typedef enum {
  PASS_ALWAYS = 0,
  PASS_COLOR,
  PASS_TRANSFORM,
  PASS_KEY,
  PASS_GIVE,
  PASS_NEXTLEVEL,
  PASS_SOLID,
  PASS_BREAK,
  PASS_PUSH
} collision_type;

typedef enum {
  PA = PASS_ALWAYS,
  PC = PASS_COLOR,
  PT = PASS_TRANSFORM,
  PK = PASS_KEY,
  PG = PASS_GIVE,
  PN = PASS_NEXTLEVEL,
  PS = PASS_SOLID,
  PB = PASS_BREAK,
  PP = PASS_PUSH
} collision_type_short;

Color tilecolors[NUM_BLOCKS][MAX_DATAVALS] = {
    {BLACK},
    {WHITE,WHITE,LIGHTGRAY,WHITE},
    {GOLD,ORANGE,RED,MAGENTA,VIOLET,BLUE,GREEN},
    {GOLD,ORANGE,RED,MAGENTA,VIOLET,BLUE,GREEN},
    {GOLD,ORANGE,RED,MAGENTA,VIOLET,BLUE,GREEN},
    {GOLD,ORANGE,RED,MAGENTA,VIOLET,BLUE,GREEN},
    {WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE},
    {WHITE},
    {},
    {WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE},
    {WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE},
    {WHITE,WHITE,WHITE,WHITE}
};

Color worldcolors[] = {
    WHITE,GOLD,ORANGE,RED,MAGENTA,VIOLET,BLUE,GREEN,BLACK
};

int tileparams[NUM_BLOCKS][MAX_DATAVALS] = {
    {0},
    {0,0,0,0},
    {1,2,3,4,5,6,7},
    {1,2,3,4,5,6,7},
    {0,1,2,3,4,5,6},
    {0,1,2,3,4,5,6},
    {0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0},
    {0},
    {0,0},
    {0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0},
    {0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0},
    {0,0,0,0}
};

int tilecollision[NUM_BLOCKS][MAX_DATAVALS] = {
  {PA},
  {PS,PP,PB,PS},
  {PC,PC,PC,PC,PC,PC,PC},
  {PT,PT,PT,PT,PT,PT,PT},
  {PG,PG,PG,PG,PG,PG,PG},
  {PK,PK,PK,PK,PK,PK,PK},
  {PN,PN,PN,PN,PN,PN,PN,PN,PN,PN,PN,PN,PN,PN,PN,PN},
  {PS},
  {PS,PS},
  {PA,PA,PA,PA,PA,PA,PA,PA,PA,PA,PA,PA,PA,PA,PA,PA,PA,PA,PA,PA,PA,PA,PA,PA,PA,PA},
  {PA,PA,PA,PA,PA,PA,PA,PA,PA,PA,PA,PA,PA,PA,PA,PA,PA,PA,PA,PA,PA,PA,PA,PA,PA,PA},
  {PA,PA,PA,PA}
};
